name: build
run-name: Create React App build.
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - run: |
            npm i 
            npm run dev
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "[actions]: update Readme"
            git push
