name: Pages Build
run-name: Building new pages
on:
  push:
    branches:
      - master

jobs:
  pages-build:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 16
        run: |
         npm i 
         npm run build
         git config user.name github-actions
         git config user.email github-actions@github.com
         git checkout -B gh-pages
         git add build
         git commit -m "Build by Abhijith Ganesh🚀🚀🚀"
         git push
    
       
